name: vivarium_control_unit
description: Vivarium Control App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_core: "^1.10.0"
  firebase_auth: "^3.2.0"
  firebase_messaging: ^11.1.0
  firebase_database: ^8.1.0
  firebase_storage: ^10.1.0

  #notifications
  flutter_local_notifications: ^9.1.2

  #Permissions
  permission_handler: ^8.3.0

  #Provider
  provider: ^6.0.1

  #Google
  google_sign_in: ^5.2.1

  # Font & Icons
  font_awesome_flutter: ^9.2.0

  #Bluetooth
  flutter_reactive_ble: ^3.1.0

  #Bluetooth enabler
  flutter_blue_elves: ^0.1.4

  #Toast
  fluttertoast: ^8.0.8

  #Navigation bar
  bottom_navy_bar: ^6.0.0

  #Charts - null safety missing
  fl_animated_linechart:
    git:
      url: https://github.com/JacobJust/fl_animated_linechart

  #Grid view
  flutter_staggered_grid_view: ^0.4.1

  #Color picker
  flex_color_picker: ^2.2.0

  #Date Time picker
  date_time_picker: ^2.1.0

  #Confirm dialog
  confirm_dialog: ^1.0.0

  #Settings
  app_settings: ^4.1.1

  #Location request
  location: ^4.3.0

  #Check tank
  flutter_background_service: ^0.1.5

  #check internet connection
  connectivity_plus: ^2.0.3

dev_dependencies:
#  lints: ^1.0.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/background/main_full.jpg
    - assets/icons/circle/aquarium_512.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
